# Generated by Django 2.2.5 on 2019-10-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersdetails',
            old_name='city',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='usersdetails',
            name='state',
        ),
    ]
