# Generated by Django 2.2.5 on 2019-10-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20191018_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersdetails',
            old_name='firstname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='usersdetails',
            name='lastname',
        ),
    ]
